-- 0. 전자문서, 전자문서댓글 테이블 및 시퀀스 드랍
DROP TABLE ELECDOCU CASCADE CONSTRAINTS; -- 전자문서
DROP SEQUENCE DOCUSEQ_ELECDOCU;
DROP TABLE ELECDOCUREPLY CASCADE CONSTRAINTS; -- 전자문서댓글
DROP SEQUENCE REPLYSEQ_ELECDOCUREPLY;
DROP TABLE ELECDOCUCONF CASCADE CONSTRAINTS; -- 전자문서 결재라인
DROP SEQUENCE CONFSEQ_ELECDOCUCONF;
DROP TABLE ELECDOCUCRTD CASCADE CONSTRAINTS; -- 전자문서 연관문서
DROP SEQUENCE RELATEDNUM_ELECDOCURTD;

ALTER TABLE ELECDOCU DROP COLUMN CONFIRMLINE

-- 1. 전자문서 테이블 및 시퀀스 생성
CREATE TABLE ELECDOCU(
    -- PK
    DOCUSEQ NUMBER(4) PRIMARY KEY,
     
    -- FK
    USERNO NUMBER(4) NOT NULL,
    JOBCODE NUMBER(4) NOT NULL,
    DEPTCODE NUMBER(4) NOT NULL,
    WPCODE NUMBER(4) NOT NULL,
    CONFSEQ NUMBER(4) NOT NULL,
    RELATEDNUM VARCHAR2(20) NOT NULL,  -- 2021080213051108 // 실제 PK는 아니나, 연관문서 연결 시 필요한 고유번호
    
    WRITEDATE DATE NOT NULL, -- 자동으로 SYSDATE
    UPDATEDATE DATE, -- 상신일자, 자동으로 SYSDATE

    REFEREE VARCHAR2(300),
    COOPERATOR VARCHAR2(300),
      
    CATEGORY VARCHAR2(50) NOT NULL,
    PERIOD VARCHAR2(50) NOT NULL,
    RELATED VARCHAR2(150), --연관글번호 RELATEDNUM을 끌어와서 저장, 최대 5개까지만 연결 가능
    TITLE VARCHAR2(400) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    FILENAME VARCHAR2(600),
    NEWFILENAME VARCHAR2(600),
    DEL NUMBER(1) -- 미상신 시만 기능
);
CREATE SEQUENCE DOCUSEQ_ELECDOCU
START WITH 1
INCREMENT BY 1;
-- 2. 전자문서댓글 테이블 및 시퀀스 생성
CREATE TABLE ELECDOCUREPLY(
    -- PK
    REPLYSEQ NUMBER(2) PRIMARY KEY,
     
    -- FK
    DOCUSEQ NUMBER(4) NOT NULL,
    USERNO NUMBER(4) NOT NULL,
    JOBCODE NUMBER(4) NOT NULL,
    DEPTCODE NUMBER(4) NOT NULL,
    WPCODE NUMBER(4) NOT NULL,
    
    -- 댓글깊이
    REF NUMBER(3) NOT NULL,
    STEP NUMBER(1) NOT NULL,
    DEPTH NUMBER(1) NOT NULL,
    
    REPLYCONTENT VARCHAR2(600),
    REPLYFILENAME VARCHAR2(600),
    REPLYNEWFILENAME VARCHAR2(600),
     
    REPLYDATE DATE NOT NULL,
    REPLYDEL NUMBER(1) NOT NULL
);
CREATE SEQUENCE REPLYSEQ_ELECDOCUREPLY
START WITH 1
INCREMENT BY 1;

-- 3. 전자문서 결재라인

CREATE TABLE ELECDOCUCONF(
	CONFSEQ NUMBER(4) PRIMARY KEY,
	DOCUSEQ NUMBER(4) NOT NULL,
    USERNO NUMBER(4) NOT NULL,
    JOBCODE NUMBER(4) NOT NULL,
    DEPTCODE NUMBER(4) NOT NULL,
    WPCODE NUMBER(4) NOT NULL,
    CHECKING NUMBER(1) NOT NULL,
    STATEMENT NUMBER(1) NOT NULL
);
CREATE SEQUENCE CONFSEQ_ELECDOCUCONF
START WITH 1
INCREMENT BY 1;

-- 4. 전자문서 연관된문서
CREATE TABLE ELECDOCURTD(
	RELATEDNUM VARCHAR2(20) PRIMARY KEY,
	DOCUSEQ NUMBER(4) NOT NULL
);
CREATE SEQUENCE RELATEDNUM_ELECDOCURTD
START WITH 1
INCREMENT BY 1;

-- 5. 전자문서, 전자문서댓글, 관리자테이블 외래키 설정
-- 전자문서 외래키
ALTER TABLE ELECDOCU -- 유저
ADD CONSTRAINT FK_ELECDOCU_USERNO FOREIGN KEY(USERNO)
REFERENCES TB_USER(USERNO);
ALTER TABLE ELECDOCU -- 잡
ADD CONSTRAINT FK_ELECDOCU_JOBCODE FOREIGN KEY(JOBCODE)
REFERENCES TB_JOB(JOBCODE);
ALTER TABLE ELECDOCU -- 부서
ADD CONSTRAINT FK_ELECDOCU_DEPTCODE FOREIGN KEY(DEPTCODE)
REFERENCES TB_DEPARTMENT(DEPTCODE);
ALTER TABLE ELECDOCU -- 근무처
ADD CONSTRAINT FK_ELECDOCU_WPCODE FOREIGN KEY(WPCODE)
REFERENCES TB_WORKPLACE(WPCODE);
ALTER TABLE ELECDOCU -- 결재라인
ADD CONSTRAINT FK_ELECDOCU_CONFSEQ FOREIGN KEY(CONFSEQ)
REFERENCES ELECDOCUCONF(CONFSEQ);
ALTER TABLE ELECDOCU -- 연관문서
ADD CONSTRAINT FK_ELECDOCU_RELATEDNUM FOREIGN KEY(RELATEDNUM)
REFERENCES ELECDOCURTD(RELATEDNUM);
-- 리플 외래키
ALTER TABLE ELECDOCUREPLY -- 전자문서
ADD CONSTRAINT FK_ELECDOCUREPLY_DOCUSEQ FOREIGN KEY(DOCUSEQ)
REFERENCES ELECDOCU(DOCUSEQ);
ALTER TABLE ELECDOCUREPLY -- 유저
ADD CONSTRAINT FK_ELECDOCUREPLY_USERNO FOREIGN KEY(USERNO)
REFERENCES TB_USER(USERNO);
ALTER TABLE ELECDOCUREPLY -- 잡
ADD CONSTRAINT FK_ELECDOCUREPLY_JOBCODE FOREIGN KEY(JOBCODE)
REFERENCES TB_JOB(JOBCODE);
ALTER TABLE ELECDOCUREPLY -- 부서
ADD CONSTRAINT FK_ELECDOCUREPLY_DEPTCODE FOREIGN KEY(DEPTCODE)
REFERENCES TB_DEPARTMENT(DEPTCODE);
ALTER TABLE ELECDOCUREPLY -- 근무처
ADD CONSTRAINT FK_ELECDOCUREPLY_WPCODE FOREIGN KEY(WPCODE)
REFERENCES TB_WORKPLACE(WPCODE);
-- 결재자 외래키
ALTER TABLE ELECDOCUCONF -- 전자문서
ADD CONSTRAINT FK_ELECDOCUCONF_DOCUSEQ FOREIGN KEY(DOCUSEQ)
REFERENCES ELECDOCU(DOCUSEQ);
ALTER TABLE ELECDOCUCONF -- 유저
ADD CONSTRAINT FK_ELECDOCUCONF_USERNO FOREIGN KEY(USERNO)
REFERENCES TB_USER(USERNO);
ALTER TABLE ELECDOCUCONF -- 잡
ADD CONSTRAINT FK_ELECDOCUCONF_JOBCODE FOREIGN KEY(JOBCODE)
REFERENCES TB_JOB(JOBCODE);
ALTER TABLE ELECDOCUCONF -- 부서
ADD CONSTRAINT FK_ELECDOCUCONF_DEPTCODE FOREIGN KEY(DEPTCODE)
REFERENCES TB_DEPARTMENT(DEPTCODE);
ALTER TABLE ELECDOCUCONF -- 근무처
ADD CONSTRAINT FK_ELECDOCUCONF_WPCODE FOREIGN KEY(WPCODE)
REFERENCES TB_WORKPLACE(WPCODE);
-- 연관문서 외래키
ALTER TABLE ELECDOCURTD -- 전자문서
ADD CONSTRAINT FK_ELECDOCURTD_DOCUSEQ FOREIGN KEY(DOCUSEQ)
REFERENCES ELECDOCU(DOCUSEQ);
 


ALTER TABLE TB_USER DROP COLUMN DEL;
-- 테이블 생성
CREATE TABLE TB_USER(
USERNO NUMBER(4),
USERPW  VARCHAR2(50) NOT NULL,
USERNAME VARCHAR2(50) NOT NULL,
USEREMAIL VARCHAR2(50) UNIQUE,
USERTEL VARCHAR2(30),
USERADDRESS VARCHAR2(300),
USERPHONE VARCHAR2(30),
USERHIREDATE DATE NOT NULL,
USERENDDATE DATE,
USERCURRWORK NUMBER(1) NOT NULL,
USERAUTH NUMBER(4) NOT NULL,
DEPTCODE NUMBER(4) NOT NULL,
JOBCODE NUMBER(4) NOT NULL,
COMCODE NUMBER(4) NOT NULL,
WPCODE NUMBER(4) NOT NULL
);
-- PK
ALTER TABLE TB_USER ADD CONSTRAINT USER_UNO_PK PRIMARY KEY(USERNO);
-- FK
ALTER TABLE TB_USER ADD CONSTRAINT USER_CCD_FK FOREIGN KEY(COMCODE) REFERENCES TB_COMPANY(COMCODE);
ALTER TABLE TB_USER ADD CONSTRAINT USER_WCD_FK FOREIGN KEY(WPCODE) REFERENCES TB_WORKPLACE(WPCODE);
ALTER TABLE TB_USER ADD CONSTRAINT USER_DCD_FK FOREIGN KEY(DEPTCODE) REFERENCES TB_DEPARTMENT(DEPTCODE);
ALTER TABLE TB_USER ADD CONSTRAINT USER_JCD_FK FOREIGN KEY(JOBCODE) REFERENCES TB_JOB(JOBCODE);
ALTER TABLE TB_USER ADD CONSTRAINT USER_UAT_FK FOREIGN KEY(USERAUTH) REFERENCES TB_AUTHORITY(USERAUTH);
-- 시퀀스 생성
CREATE SEQUENCE SEQ_USER
START WITH 1000
INCREMENT BY 1
MAXVALUE 1999;
-- 삭제
DROP TABLE TB_USER CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_USER;
-- 보기
SELECT * FROM TB_USER;
--****************************************************************************
-- 테이블 생성
CREATE TABLE TB_COMPANY(
COMCODE NUMBER(4),
COMNAME VARCHAR2(50) NOT NULL,
COMREP VARCHAR2(50) NOT NULL,
COMTEL VARCHAR2(30) NOT NULL,
DEL NUMBER(1) NOT NULL
);
-- PK
ALTER TABLE TB_COMPANY ADD CONSTRAINT COMPANY_CCD_PK PRIMARY KEY(COMCODE);
-- NO FK
-- 시퀀스 생성
CREATE SEQUENCE SEQ_COMPANY
START WITH 2000
INCREMENT BY 1
MAXVALUE 2999;
-- 삭제
DROP TABLE TB_COMPANY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_COMPANY;
-- 보기
SELECT * FROM TB_COMPANY;
--****************************************************************************
-- 테이블 생성
CREATE TABLE TB_WORKPLACE(
WPCODE NUMBER(4),
WPNAME VARCHAR2(50) NOT NULL,
WPREP VARCHAR2(50) NOT NULL,
WPTEL VARCHAR2(30) NOT NULL,
COMCODE NUMBER(4) NOT NULL,
DEL NUMBER(1) NOT NULL
);
-- PK
ALTER TABLE TB_WORKPLACE ADD CONSTRAINT WORKPLACE_WCD_PK PRIMARY KEY(WPCODE);
-- FK
ALTER TABLE TB_WORKPLACE ADD CONSTRAINT WORKPLACE_CCD_FK FOREIGN KEY(COMCODE) REFERENCES TB_COMPANY(COMCODE);
-- 시퀀스 생성
CREATE SEQUENCE SEQ_WORKPLACE
START WITH 3000
INCREMENT BY 1
MAXVALUE 3999;
-- 삭제
DROP TABLE TB_WORKPLACE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_WORKPLACE;
-- 보기
SELECT * FROM TB_WORKPLACE;
--****************************************************************************
-- 테이블 생성
CREATE TABLE TB_DEPARTMENT(
DEPTCODE NUMBER (4),
DEPTNAME VARCHAR2(200) NOT NULL,
COMCODE NUMBER (4) NOT NULL,
WPCODE NUMBER (4) NOT NULL,
PARENTDEPT NUMBER(4),
DEL NUMBER(1) NOT NULL
);
-- PK
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT DEPARTMENT_DCD_PK PRIMARY KEY(DEPTCODE);
-- FK
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT DEPARTMENT_CCD_FK FOREIGN KEY(COMCODE) REFERENCES TB_COMPANY(COMCODE);
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT DEPARTMENT_WCD_FK FOREIGN KEY(WPCODE) REFERENCES TB_WORKPLACE(WPCODE);
-- 시퀀스 생성
CREATE SEQUENCE SEQ_DEPARTMENT
START WITH 4000
INCREMENT BY 1
MAXVALUE 4999;
-- 삭제
DROP TABLE TB_DEPARTMENT CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_DEPARTMENT;
-- 보기
SELECT * FROM TB_DEPARTMENT;
--****************************************************************************
-- 테이블 생성
CREATE TABLE TB_AUTHORITY(
USERAUTH NUMBER(4),
AUTHNAME VARCHAR2(100) NOT NULL,
OPTIONA NUMBER(1) NOT NULL,
OPTIONB NUMBER(1) NOT NULL,
OPTIONC NUMBER(1) NOT NULL,
DEL NUMBER(1) NOT NULL
);
-- PK
ALTER TABLE TB_AUTHORITY ADD CONSTRAINT AUTHORITY_UAT_PK PRIMARY KEY(USERAUTH);
-- NO FK
-- 시퀀스 생성
CREATE SEQUENCE SEQ_AUTHORITY
START WITH 5000
INCREMENT BY 1
MAXVALUE 5999;
-- 삭제
DROP TABLE TB_AUTHORITY CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_AUTHORITY;
-- 보기
SELECT * FROM TB_AUTHORITY;
--****************************************************************************
-- 테이블 생성
CREATE TABLE TB_JOB(
JOBCODE NUMBER(4),
JOBPOSITION VARCHAR2(50) NOT NULL,
JOBTITLE VARCHAR2(50) NOT NULL,
DEL NUMBER(1) NOT NULL
);
-- PK
ALTER TABLE TB_JOB ADD CONSTRAINT JOB_JCD_PK PRIMARY KEY(JOBCODE);
-- NO FK
-- 시퀀스 생성
CREATE SEQUENCE SEQ_JOB
START WITH 6000
INCREMENT BY 1
MAXVALUE 6999;
-- 삭제
DROP TABLE TB_JOB CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_JOB;
-- 보기
SELECT * FROM TB_JOB;
--****************************************************************************